---
name: Capture-Tiny
version: 0.05_51
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: 'Capture STDOUT and STDERR from Perl, XS or external programs'
license: apache
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Capture-Tiny
  repository: http://github.com/dagolden/capture-tiny/
requires:
  Exporter: 0
  File::Spec: 0
  File::Temp: 0.14
  IO::Handle: 0
  perl: 5.006
build_requires:
  Test::More: 0.62
provides:
  Capture::Tiny:
    file: lib/Capture/Tiny.pm
    version: 0.05_51
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
